### ISSUE TITLE
Hide text container causes unexpected size (min size apparently)

### ISSUE THREAD

**Issue by pittMarson** [patrickmarabeas/ng-FitText.js#13]
I observed that when I hide a parent of the text, I sometimes (but not always) have an unexpected resize to the min size.
The hiding is done with some animations (slide / fade), and I suspect when showing again the fit routine is never called. Resizing the window works fine but I can't expect that from my users :)
Also to provoke this, you can : hide, resize the window, show.
Do you know any workaround ?

**Comment by patrickmarabeas** [comment]
Should no longer be an issue.
