### ISSUE TITLE
using with line break

### ISSUE THREAD

**Issue by mcneela86** [patrickmarabeas/ng-FitText.js#14]
Is there a way to have a line break inside my fittext?

Is have some text that I want to display all the same size but on two lines, for example:
<p data-fittext>some<br>random text</p>

the outcome I need is (all the text the same size):
     some
random text

But doing this makes the text appear very large.

Can someone help?

**Comment by patrickmarabeas** [comment]
Line breaks now work in v3.2.0 with min font size specifications, see demo (type in input): http://patrickmarabeas.github.io/ng-FitText.js/ but isn't something you can specify as to where it occurs.

To be able to specify we need to divide the ratio by the number of line breaks. Are you simply using `<br>`'s? The other option would be to look for data attributes which could be specified on any element... 


    <span data-fittext>
        <span data-fittext-sub>Line 1</span>
        <span data-fittext-sub>Line 2 that's longer</span>
    </span>

Let me know what you think...

**Comment by patrickmarabeas** [comment]
v3.3.0 adds `data-fittext-nl` attribute. Wrap each new line in a span/wrapper of some sort and include the attribute. See demo page for example: http://patrickmarabeas.github.io/ng-FitText.js/
