### ISSUE TITLE
font size isn't set

### ISSUE THREAD

**Issue by lynndylanhurley** [patrickmarabeas/ng-FitText.js#15]
Please correct me if I'm wrong, but my understanding is that this library should shrink text to fit within the width of an element. If I'm mistaken, feel free to close this issue.

### issue:
This "lorem ipsum" text should be contained within the dark area.

![web view](http://i.imgur.com/MiP8DMI.png)

The text element itself is the width of the dark area (~280px).

### code:

~~~javascript
// config
angular.module('app')
  .config(function(fitTextConfigProvider) {
    fitTextConfigProvider.config = {
      debounce: _.debounce
    };
  })
~~~

~~~html
<!-- view -->
<h1 data-fittext ng-model='user.name' ng-bind='user.name'></h1>
~~~

CSS (from web inspector):
![CSS View](http://i.imgur.com/qmPl7iy.png)

The following styles are set by this module:

~~~css
{
  display: inline-block;
  white-space: nowrap;
  line-height: 1;
}
~~~

Notice that "font-size" property is absent. The rest of the styles were defined in the CSS of my app.

EDIT: I should also note that no errors have been thrown.

**Comment by olsh** [comment]
@lynndylanhurley probably, the problem is in **width: 100%**. Try to set it in auto.

**Comment by patrickmarabeas** [comment]
New version (3.2.0) is out, let me know if you are still having issues. If so, see if you can work off of the demo to narrow down the issue further...

**Comment by Hiieu** [comment]
still not fixed I got same problem. Text go out from div. 
If one line word is long. For example: aaaaaaaaaaaaaaaaaaa|outside
