### ISSUE TITLE
Min Size and line break

### ISSUE THREAD

**Issue by waltercolindres** [patrickmarabeas/ng-FitText.js#16]
I set a min size to 30 and it breaks outside of the container element on mobile. How can I get it to do lines breaks automatically?

**Comment by patrickmarabeas** [comment]
No doubt it'll be regarding `element[0].style.whiteSpace = 'nowrap';`. Without testing, you might find success in removing some of the forced styling in the module. I didn't have wrapping in mind when I developed this.

I shouldn't be too far off having a spot of time to dig into some of the current issues.

**Comment by waltercolindres** [comment]
Thanks! I appreciate the quick reply!

**Comment by patrickmarabeas** [comment]
This should now be fixed in v3.2.0: https://github.com/patrickmarabeas/ng-FitText.js/releases/tag/3.2.0 

You can see it live in the demo (type in the input): http://patrickmarabeas.github.io/ng-FitText.js/

**Comment by waltercolindres** [comment]
Awesome!
