### ISSUE TITLE
Can't have multiple directives on page

### ISSUE THREAD

**Issue by waltercolindres** [patrickmarabeas/ng-FitText.js#17]
I am trying to use the directive on more than one headline on a page.

It will resize the first, but not the second.

Any recommendations?

**Comment by patrickmarabeas** [comment]
Are you getting any console errors?

The demo shows multiple being used on a page. Can't be much help unless you can replicate the issue in a Plnkr or something...

**Comment by waltercolindres** [comment]
No errors. 

I am using the attribute method:
data-fittext data-fittext-max="90" data-fittext-min="40"

**Comment by patrickmarabeas** [comment]
You'll have to replicate the issue: http://jsfiddle.net/

If you are sticking any other directives on the element, try removing them / putting them on another element wrapper etc
