### ISSUE TITLE
Doesn't work within ng-view

### ISSUE THREAD

**Issue by robertfmurdock** [patrickmarabeas/ng-FitText.js#24]
I've been having trouble getting this to work tonight, and after some experiments I discovered that I get great results when using this everywhere BUT within an ng-view. That is to say, with identical elements and css text will resize correctly outside of an ng-view but incorrectly within one. The text will render at font-size 10 and doesn't seem to respond to any prompting, including it seemingly ignores the data-fittext-max and data-fittext-min attributes.

Sorry I don't have time tonight to whip up an example to illustrate what I'm seeing, just thought I'd drop off the intel.

**Comment by aviadhahami** [comment]
:+1: Having same issue

**Comment by aviadhahami** [comment]
@robertfmurdock I worked around this by using ng-model and inline binding. i.e :
 <h1 data-ng-model="test" fittext>{{test}}</h1>

**Comment by patrickmarabeas** [comment]
`data-ng-model="test"` should be `data-ng-bind="test"` with no need of `{{test}}`. Bit of a spud moment on my behalf there... v4.x will have the correct watcher and require proper attr usage.
