### ISSUE TITLE
dynamically call ng-fitText 

### ISSUE THREAD

**Issue by louisdoe** [patrickmarabeas/ng-FitText.js#43]
Hi

how to dynamically call ng-fitText to resize some text that has been dynamically insterted ?

thanks

**Comment by louisdoe** [comment]
Is it possible to "refresh" the action of ng-fitText please ?

**Comment by patrickmarabeas** [comment]
Could you create a demo (jsfiddle etc) to demonstrate the requirement / issue?

**Comment by louisdoe** [comment]
yes here it is: http://codepen.io/LouisDoe/pen/rxGQpZ

**Comment by patrickmarabeas** [comment]
http://codepen.io/anon/pen/wMrQRq

- Need to include the module
- Model needed to be defined outside of the `showPopup` method
- Max size was set to 17px - wayyyy too low ; )
- Need to use `data-ng-model="data.proModel"` attribute for dynamic text. This is a bug, though - as both `ng-model` *and* `{{}}` binding shouldn't be required for dynamic text to work properly

Have a look at the demo page in the repo for more examples.

**Comment by patrickmarabeas** [comment]
I see I spudded out when I added the dynamic stuff. `ngModel` instead of `ngBind`. Duhh.

**Comment by louisdoe** [comment]
Thanks a lot @patrickmarabeas, so the solution to my problem was to add data-ng-model="" to my element so it can dynamically resize.

**Comment by louisdoe** [comment]
@patrickmarabeas how should I do if there are several variable like this:

    <div class="fittedRes" data-fittext data-fittext-max="12">
	  {{computed.userLengthFtin}} x {{computed.userWidthFtin}} x {{computed.userThickFtin}}
    </div>

**Comment by patrickmarabeas** [comment]
Exactly the same. `data-ng-model="computed.userLengthFtin + ' x ' + ... "`

**Comment by louisdoe** [comment]
ok perfect, thanks Patrick !
