### ISSUE TITLE
The behavior of Jade may prevent this module to work out of the box

### ISSUE THREAD

**Issue by poupougnac** [patrickmarabeas/ng-FitText.js#47]
Hi, thank you for this module.

I had to investigate to understand why this module doesn't worked "out of the box". Just by adding data-fittext as a directive on my element. 

It appears that Jade compiles data-fittext as data-fittext="data-fittext" in HTML in order to support older browser (they don't like empty attribute). I would suggest to use a specific attribute name for the compressor value instead of using the default directive attribute value.

It's not a big deal but Jade is quite popular and it will probably save some time to other people in the exact same situation :)

Regards,

**Comment by dogancelik** [comment]
:+1: for Jade support

**Comment by case12** [comment]
I was able to get around this by doing inline tags in my jade file.

`| <h1 data-fittext>This worked for me</h1>`

**Comment by patrickmarabeas** [comment]
Eep, forgot about this issue sorry. Should be an easy fix by ensuring that the value is a number || 1.

**Comment by patrickmarabeas** [comment]
Fix has been published.
