### ISSUE TITLE
Provide new version on npm

### ISSUE THREAD

**Issue by pmlamotte** [patrickmarabeas/ng-FitText.js#49]
We would like to use ng-FitText, but noticed that the npm version is quite out of date and we don't make use of bower. Is there a chance we could get an updated npm version available?

**Comment by patrickmarabeas** [comment]
Certainly - expect an update within the next 12 hours.

**Comment by patrickmarabeas** [comment]
Updated : )

**Comment by pmlamotte** [comment]
Thanks a lot!
